[package]
name = "gaia"
version = "0.1.2"
edition = "2024"

[dependencies]
colored = "3.0.0"
flate2 = "1.1.10"
json = "0.12.4"
reqwest = { version = "0.13.5", features = ["blocking"] }
tar = "0.4.46"
xz = "0.1.0"

[profile.release]
opt-level = "z"
codegen-units = 1
[profile.release.package."*"]
opt-level = "z"
codegen-units = 1
